@startuml
set namespaceSeparator none

hide method

namespace users.service.model.domain {

    class Sale {
        - id: Long
        - numberSale: Long
        - createdDate: Date
    }

    class Employee {
        - userId: long
        - position: String
    }

    class Client {
        - lastPurchase: Date
    }

    abstract class Person {
        - id: Long
        - email: String
        - firstName: String
        - lastName: String
        - male: Male
        - isDeleted: Boolean
        - createdDate: Date
    }

    class Detail {
        - id: Long
        - totalProducts:Integer
        - totalPrice: Long
    }

    Client -up-|> Person

    Employee -up-|> Person

     Sale *-right-> Employee : employee
     Sale *--> Client : client

    Detail *-down-> Sale : sale
}
@enduml